# Generated by Django 3.0.8 on 2020-08-14 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('craigslistclone', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={'verbose_name_plural': 'Searches'},
        ),
    ]
